---
title: "TDCS and Memory"
author: "Kyle Kurkela"
date: "9/13/2017"
output: word_document
bibliography: ./citations.bib
---

# Introduction

Over the past decade, there has been an increase interest in the use of transcranial direct current stimulation (tDCS) to study long-term, declarative memory. Studies that use tDCS to study declarative memory are wide-randing and idiosyncratic on the specific parameters used, with studies using a variety of memory paradigms (e.g., DRM, RIF, and item-method directed forgetting), dependent variables (e.g., proportion recalled, rection time, d'), electrode montages (e.g., anodal-dlPFC, cathodal-PPC), and stimulation timings (encoding, retrieval, consolidation). Overall, the results on the effectiveness of tDCS on declartive memory are mixed at best and may depend on study parameters.  

In terms of electrode montages, tDCS studies of declarative memory typically target either the lPFC (@elmer2009, @brambilla2015, @hammer2011, @matzen2015, @javadi2012, @eggert2013, @prehn2014, @garside2015, @sahlem2015, @gray2015, @lu2015, @manenti2013, @sandrini2014, @marshall2004, @marshall2011, @lafontaine2013, @penolazzi2014, @zwissler2014, @nikolin2015, @morgan2014, @ladenbauer2017, @pergolizzi2017, @gaynor2017, @marangolo2013) or the PPC (@brambilla2015, @england2015, @jacobson2012, @schaal2015, @manenti2013, @minamoto2014, @pergolizzi2015, @pisoni2015) with only a handful targeting other cortical areas such as the temoral lobes (@del2015, @ross2011, @nikolin2015, @ross2010, @pisoni2015, @boggio2009). Montages also differ in terms of laterality, with some targeting specific hemispheres with anodal stimulation (right- citations; left- citations), some targeting both hemispheres with some combination of anodal and cathodal stimulation, and others  

In terms of stimulation timings, an even mix of tDCS studies of declarartive memory have focused on stimulation near the time of encoding (@elmer2009, @england2015, @hammer2011, @jacobson2012, @matzen2015, @javadi2012, @lu2015, @minamoto2014, @zwissler2014, @pisoni2015, @boggio2009, @penolazzi2010, @lafontaine2013, @morgan2014, @gaynor2017), retrieval (@brambilla2015, @javadi2012, @wais2011, @gray2015, @schaal2015, @ross2011, @manenti2013, @fiori2011, @penolazzi2014, @pergolizzi2015, @boggio2009, @pisoni2015, @marangolo2013, @pergolizzi2017) and some sort of interveining consolidation period (@stramaccia2017, @ross2010, @nikolin2015, @penolazzi2014, @sandrini2014), with the majority of consolidation studies interested in the effects of some form of tDCS during interveining sleep (@eggert2013, @prehn2014, @garside2015, @sahlem2015, @del2015, @marshall2004, @marshall2011, @ladenbauer2017).  

# References